spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/demo"
    username: "demo"
    password: "demo"
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    liquibase-schema: public
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.xml
